"""界面英文翻译表（由构建脚本生成，请勿手工调整格式）。

键＝中文原文，值＝英文；生成方式见仓库 README 的「多语言」一节。
条目按中文排序，便于人工校对；``{0}``/``{1}`` 是插值占位符，
必须与键中的编号保持一致（i18n.trf 会用它做格式化）。
"""

from __future__ import annotations

CATALOG: dict[str, str] = {
    '        建议：{0}': '        Recommendation: {0}',
    ' 分钟': ' min',
    ' 项问题：': ' issue(s): ',
    '\'">打开哔哩哔哩测试视频</button>': '\'">Open bilibili test video</button>',
    "'currentTime = ' + v.currentTime.toFixed(2) + ' 秒\u3000' +": "'currentTime = ' + v.currentTime.toFixed(2) + ' s\u3000' +",
    "'error = ' + (v.error ? (v.error.code + ' / ' + v.error.message) : '无');": "'error = ' + (v.error ? (v.error.code + ' / ' + v.error.message) : 'none');",
    "'尺寸 = ' + v.videoWidth + '×' + v.videoHeight + '\u3000' +": "'size = ' + v.videoWidth + '×' + v.videoHeight + '\u3000' +",
    '* .NET 运行时（.NET Framework 或 .NET）是否可用；': '* whether a .NET runtime (.NET Framework or .NET) is available;',
    '* 实测 ``canPlayType`` 与 ``MediaSource.isTypeSupported`` 对': '* tests ``canPlayType`` and ``MediaSource.isTypeSupported`` support for',
    '* 快捷键一览 —— 扫描主窗口里所有带快捷键的 QAction；': '* Keyboard shortcuts - scans every QAction in the main window that has a shortcut;',
    '* 搜索引擎 / User-Agent 预设 —— 读取配置与 ``useragent.UA_PRESETS``。': '* Search engines / User-Agent presets - read from the configuration and ``useragent.UA_PRESETS``.',
    '* 播放一段测试视频，并给出针对性的排查建议。': '* plays a test video and gives targeted troubleshooting suggestions.',
    '* 操作系统与位数是否满足要求；': '* whether the OS and its bitness meet the requirements;',
    '* 是否具备 pythonnet / clr_loader / cffi 互操作组件；': '* whether the pythonnet / clr_loader / cffi interop components are available;',
    '* 显示当前渲染引擎、WebView2 版本、User-Agent；': '* shows the current rendering engine, WebView2 version, User-Agent;',
    '* 渲染引擎 —— 读取 ``engine.ENGINE_LABELS`` 与当前内核能力；': "* Rendering engine - reads ``engine.ENGINE_LABELS`` and the current engine's capabilities;",
    '* 用户数据目录是否可写。': '* whether the user data directory is writable.',
    '* 界面风格 —— 读取 ``theme.theme_names()``；': '* UI style - reads ``theme.theme_names()``;',
    '* 系统是否安装了 **WebView2 运行时**（读注册表，含用户级安装）；': '* whether the **WebView2 Runtime** is installed on the system (reads the registry, including per-user installs);',
    '* 随程序分发的 WebView2 SDK 程序集与加载器 DLL 是否齐全；': '* whether the WebView2 SDK assemblies and loader DLL shipped with the program are all present;',
    '.NET Framework 4.x 可用': '.NET Framework 4.x available',
    '.NET 可用，但未检测到 .NET Framework 4.x': '.NET available, but .NET Framework 4.x not detected',
    '.NET 运行时': '.NET Runtime',
    '180 天': '180 days',
    '30 天': '30 days',
    '365 天': '365 days',
    '90 天': '90 days',
    ': \'<span class="no">不支持</span>\';': ': \'<span class="no">Not supported</span>\';',
    '<b>Edge WebView2（Chromium，含 H.264/AAC）</b>，确定后<b>重启程序</b>。</li>': '<b>Edge WebView2 (Chromium, with H.264/AAC)</b>, then click OK and <b>restart the program</b>.</li>',
    '<b>MHTML 单文件</b>（.mhtml，把页面与图片样式打包成一个文件，适合存档）、': '<b>MHTML single file</b> (.mhtml, packs the page, images, and styles into one file, good for archiving),',
    "<b>{0} {1}</b>\u3000作者：{2}\u3000<span style='color:#888'>（本帮助随功能更新同步维护）</span>": "<b>{0} {1}</b>\u3000Author: {2}\u3000<span style='color:#888'>(This help is kept in sync with feature updates)</span>",
    '<b>不代表网站本身可信</b>。</li>': '<b>it does not mean the site itself is trustworthy</b>.</li>',
    '<b>完整网页</b>（html + 同名资源文件夹）、<b>仅 HTML</b>（只存 HTML）。</li>': '<b>Complete webpage</b> (html + a resource folder of the same name), <b>HTML only</b> (HTML alone).</li>',
    '<b>彻底移除了 Flash 插件接口</b>，所以"官方 Flash"无法再装进本程序，': '<b>removed the Flash plugin interface completely</b>, so "official Flash" can no longer be installed in this program,',
    '<b>清空内容即恢复内核默认值</b>。</li>': '<b>clearing the field restores the engine default</b>.</li>',
    '<b>点一下就记下这条规则</b>，按 <code>Esc</code> 取消。': '<b>one click records the rule</b>, and <code>Esc</code> cancels.',
    '<b>结论与建议</b>': '<b>Result and suggestions</b>',
    '<b>选择会被记住</b>，下次启动保持上次的模式。</li>': '<b>Your choice is remembered</b> and kept on the next launch.</li>',
    '<b>隐私提示</b>：这会让这些域名的服务器在你实际点击之前': '<b>Privacy note</b>: this means the servers for those domains',
    '<button class="ghost" id="btn-continue">我了解风险，继续访问</button>': '<button class="ghost" id="btn-continue">I understand the risk, continue anyway</button>',
    '<button class="primary" id="btn-back">返回上一页</button>': '<button class="primary" id="btn-back">Back to previous page</button>',
    '<button class="primary" id="btn-retry">重新加载</button>': '<button class="primary" id="btn-retry">Reload</button>',
    '<button id="btn-back">返回上一页</button>': '<button id="btn-back">Back to previous page</button>',
    '<button id="btn-home">回到主页</button>': '<button id="btn-home">Go to home page</button>',
    '<button onclick="document.getElementById(\'v\').play()">重新播放测试视频</button>': '<button onclick="document.getElementById(\'v\').play()">Replay test video</button>',
    '<code>LTB1</code> 魔数 + 版本 + 12 字节随机 nonce + 密文。</li>': '<code>LTB1</code> magic + version + 12-byte random nonce + ciphertext.</li>',
    '<code>env-report.txt</code> 并提示位置，': '<code>env-report.txt</code>, telling you where it is;',
    '<code>ruffle.litebrowser.local</code> 上供网页加载，': '<code>ruffle.litebrowser.local</code> for pages to load,',
    '<code>target="_blank"</code> 链接会自动开新标签页。</li>': '<code>target="_blank"</code> link inside a page opens a new tab automatically.</li>',
    '<dd>不需要，设置里改完立即生效；点「取消」会还原原来的外观。</dd>': '<dd>No, changes in the settings take effect immediately; clicking "Cancel" restores the previous appearance.</dd>',
    '<dd>会暂停，切回该标签页会自动恢复。如不需要，可在「设置 → 性能」关闭自动挂起。</dd>': '<dd>It pauses, and resumes when you switch back to that tab. If you do not need that, turn auto-suspend off in "Settings → Performance".</dd>',
    '<dd>菜单「工具 → 创建桌面快捷方式」，': '<dd>Menu "Tools → Create desktop shortcut";',
    '<dd>说明当前用的是 QtWebEngine 内核（不含 H.264）。到': '<dd>It means the QtWebEngine engine (no H.264) is in use. Go to',
    '<dd>这些内容需要先登录账号（部分还需大会员）。在页面右上角登录后即可观看。</dd>': '<dd>This content requires signing in (some of it also needs a premium membership). Sign in at the top right of the page and you can watch it.</dd>',
    '<dd>都在 <code>%APPDATA%\\LiteBrowser</code>。书签 / 历史 / 下载记录是加密的，': '<dd>It is all in <code>%APPDATA%\\LiteBrowser</code>. Bookmarks / history / download records are encrypted,',
    '<div class="hint">动一动鼠标，让小猫帮你把页面追回来 🐾</div>': '<div class="hint">Move the mouse and let the kitten chase the page back for you 🐾</div>',
    '<div class="tip" id="vstat" style="margin-top:8px">正在加载…</div>': '<div class="tip" id="vstat" style="margin-top:8px">Loading…</div>',
    '<div class="tip">提示：可在「设置 → 隐私与安全 → 可疑网址拦截」中管理黑名单与规则。</div>': '<div class="tip">Tip: you can manage the blocklist and rules under "Settings -> Privacy and Security -> Suspicious URL Blocking".</div>',
    '<div style="margin-bottom:8px"><b>测试视频</b>（H.264 + AAC）</div>': '<div style="margin-bottom:8px"><b>Test video</b> (H.264 + AAC)</div>',
    '<dt>为什么有些视频网站提示「不支持 HTML5 播放器」？</dt>': '<dt>Why do some video sites say "HTML5 player not supported"?</dt>',
    '<dt>便携版怎么创建桌面图标？</dt>': '<dt>How do I create a desktop icon for the portable version?</dt>',
    '<dt>切换主题 / 深色模式需要重启吗？</dt>': '<dt>Do I need to restart after switching theme / dark mode?</dt>',
    '<dt>后台标签页被挂起后，网页里的音乐或视频会停吗？</dt>': '<dt>When a background tab is suspended, does music or video in the page stop?</dt>',
    '<dt>哔哩哔哩的番剧、影视提示「出错啦」？</dt>': '<dt>Bilibili anime and movies say "something went wrong"?</dt>',
    '<dt>数据放在哪里？换电脑怎么带走？</dt>': '<dt>Where is the data, and how do I take it to another computer?</dt>',
    '<h1>视频播放自检</h1>': '<h1>Video Playback Self-Check</h1>',
    '<li><b>4399 小游戏</b>：老游戏页（<code>/flash/数字.htm</code>）': '<li><b>4399 mini games</b>: on old game pages (<code>/flash/number.htm</code>)',
    '<li><b>Cookie</b>：列出域名、名称、路径、是否安全、过期时间；': '<li><b>Cookie</b>: lists domain, name, path, whether it is secure, and expiry;',
    '<li><b>DNS 预解析（默认关闭）</b>：开启后会对当前页面里的链接域名做': '<li><b>DNS prefetch (off by default)</b>: when enabled, it performs',
    '<li><b>Edge WebView2</b>（默认）：使用系统自带 Edge 运行时，': '<li><b>Edge WebView2</b> (default): uses the Edge runtime that comes with Windows,',
    '<li><b>QtWebEngine</b>：随程序打包，无需系统组件，': '<li><b>QtWebEngine</b>: bundled with the program, no system components needed,',
    '<li><b>一键修复</b>：点「下载并安装 WebView2 运行时」会从微软官方下载引导安装器': '<li><b>One-click repair</b>: clicking "Download and install the WebView2 runtime" downloads the bootstrapper from Microsoft',
    '<li><b>下载完成提示</b>：完成后右下角会弹出气泡，显示文件名与保存位置，': '<li><b>Download complete notification</b>: a bubble appears at the bottom right when a download finishes, showing the file name and save location;',
    '<li><b>主密钥</b>：保存为 <code>master.key</code>，': '<li><b>Master key</b>: saved as <code>master.key</code>,',
    '<li><b>书签</b>：收藏菜单、书签栏、<code>Ctrl+D</code> 添加、整理收藏夹。</li>': '<li><b>Bookmarks</b>: the Favorites menu, the bookmarks bar, <code>Ctrl+D</code> to add, and the favorites organizer.</li>',
    '<li><b>书签栏</b>：菜单「查看 → 书签栏」显示 / 隐藏，点「整理」可编辑、删除、排序。</li>': '<li><b>Bookmarks bar</b>: menu "View → Bookmarks bar" shows / hides it; click "Organize" to edit, delete, or reorder.</li>',
    '<li><b>会话恢复</b>：在「设置 → 性能」打开后，下次启动会恢复上次的标签页': '<li><b>Session restore</b>: once enabled in "Settings → Performance", the next launch restores your last tabs',
    '<li><b>位置</b>：「设置 → 网络 → User-Agent」。</li>': '<li><b>Where</b>: "Settings → Network → User-Agent".</li>',
    '<li><b>保留策略</b>：在「设置 → 隐私与安全」中可关闭记录，或设定保留天数': '<li><b>Retention</b>: in "Settings → Privacy and security" you can turn recording off or set a number of days to keep',
    '<li><b>信息</b>：实时显示进度、已下载 / 总大小、速度与状态，': '<li><b>Details</b>: shows progress, downloaded / total size, speed, and status in real time;',
    '<li><b>入口</b>：<code>Ctrl+Shift+Del</code>、「工具 → Cookie 与缓存管理」，': '<li><b>Entry point</b>: <code>Ctrl+Shift+Del</code>, "Tools → Cookie and cache management",',
    '<li><b>全屏</b>：<code>F11</code> 或「查看 → 全屏显示」，': '<li><b>Full screen</b>: <code>F11</code> or "View → Full screen";',
    '<li><b>兼容性</b>：Ruffle 对 ActionScript 1/2 支持很好，AS3 大部分可用，': '<li><b>Compatibility</b>: Ruffle supports ActionScript 1/2 very well and most of AS3 works,',
    '<li><b>前进 / 后退 / 停止 / 刷新 / 主页</b>：工具栏按钮，均有快捷键。</li>': '<li><b>Forward / Back / Stop / Reload / Home</b>: toolbar buttons, all with keyboard shortcuts.</li>',
    '<li><b>加密对象</b>：书签、历史记录、下载记录。</li>': '<li><b>What is encrypted</b>: bookmarks, history, and download records.</li>',
    '<li><b>原理</b>：程序把 Ruffle 放在一个虚拟地址': '<li><b>How it works</b>: the program serves Ruffle from a virtual address',
    '<li><b>口令保护</b>：「设置 → 隐私与安全 → 数据加密」可设置口令': '<li><b>Passphrase protection</b>: "Settings → Privacy and security → Data encryption" lets you set a passphrase',
    '<li><b>可疑网址提示</b>：命中本地规则时会暂停打开并给出提示，规则包括黑名单命中、': '<li><b>Suspicious URL warning</b>: when a local rule matches, opening is paused and a warning is shown; the rules include blocklist hits,',
    '<li><b>名单文件</b>：<code>%APPDATA%\\LiteBrowser\\blocklist.txt</code>，': '<li><b>List file</b>: <code>%APPDATA%\\LiteBrowser\\blocklist.txt</code>,',
    '<li><b>后台播放被中断</b>：后台标签页闲置过久会被挂起以节省内存。': '<li><b>Background playback interrupted</b>: background tabs are suspended after being idle for a while to save memory.',
    '<li><b>后台标签页自动挂起</b>：闲置超过设定时间（默认 10 分钟）的标签页': '<li><b>Auto-suspend background tabs</b>: tabs idle for longer than the set time (10 minutes by default)',
    '<li><b>命令行自检</b>：在命令行执行': '<li><b>Command-line self-check</b>: run it on the command line;',
    '<li><b>地址栏</b>：输入网址回车打开；输入关键字则用默认搜索引擎搜索。</li>': '<li><b>Address bar</b>: type a URL and press Enter to open it; type keywords to search with the default search engine.</li>',
    '<li><b>多标签页</b>：支持拖动排序、中键关闭、<code>Ctrl+Tab</code> 切换。</li>': '<li><b>Multiple tabs</b>: drag to reorder, middle-click to close, <code>Ctrl+Tab</code> to switch.</li>',
    '<li><b>存储</b>：书签经 <b>AES-256-GCM</b> 加密后保存在': '<li><b>Storage</b>: bookmarks are encrypted with <b>AES-256-GCM</b> and stored in',
    '<li><b>实现</b>：WebView2 使用 InPrivate 模式，QtWebEngine 使用内存 profile。': '<li><b>Implementation</b>: WebView2 uses InPrivate mode, QtWebEngine uses an in-memory profile.',
    '<li><b>导出 PDF</b>：菜单「文件 → 导出为 PDF」。</li>': '<li><b>Export PDF</b>: menu "File → Export as PDF".</li>',
    '<li><b>平滑滚动 / 图片开关</b>：可按需开启或关闭图片以提速省流量。</li>': '<li><b>Smooth scrolling / image toggle</b>: turn images on or off as needed to speed things up and save data.</li>',
    '<li><b>开关</b>：「设置 → 网络 → Flash 兼容（Ruffle，无广告）」，默认开启；': '<li><b>Toggle</b>: "Settings → Network → Flash compatibility (Ruffle, no ads)", on by default;',
    '<li><b>开关</b>：工具栏「无痕」按钮、<code>Ctrl+Shift+N</code>，': '<li><b>Toggle</b>: the "Incognito" button on the toolbar, <code>Ctrl+Shift+N</code>,',
    '<li><b>当前版本</b>：状态栏最右侧显示（点击可打开「关于」）。</li>': '<li><b>Current version</b>: shown at the far right of the status bar (click it to open "About").</li>',
    '<li><b>怎么选元素</b>：点广告的<b>外框容器</b>最稳；': "<li><b>How to pick an element</b>: clicking the ad's <b>outer container</b> works best;",
    '<li><b>手动标记广告</b>：按 <code>Ctrl+Shift+A</code>': '<li><b>Mark ads by hand</b>: press <code>Ctrl+Shift+A</code>',
    '<li><b>打印</b>：<code>Ctrl+P</code>。WebView2 内核直接调起系统打印对话框；': '<li><b>Print</b>: <code>Ctrl+P</code>. The WebView2 engine opens the system print dialog directly;',
    '<li><b>打开</b>：<code>Ctrl+H</code> 或「工具 → 历史记录」。</li>': '<li><b>Open</b>: <code>Ctrl+H</code> or "Tools → History".</li>',
    '<li><b>打开</b>：<code>Ctrl+J</code> 或「工具 → 下载管理」。</li>': '<li><b>Open</b>: <code>Ctrl+J</code> or "Tools → Download manager".</li>',
    '<li><b>打开</b>：「设置 → 内核与环境」。</li>': '<li><b>Open</b>: "Settings → Engine and environment".</li>',
    '<li><b>拦截自动弹窗</b>：默认开启（「设置 → 隐私与安全」）。': '<li><b>Block automatic popups</b>: on by default ("Settings → Privacy and security").',
    '<li><b>按日期分组</b>：每一条都标注了打开的<b>日期（含星期）与时间</b>，': '<li><b>Grouped by date</b>: every entry is labeled with the <b>date (including day of week) and time</b> it was opened;',
    '<li><b>提示"不支持 HTML5 播放器"</b>：说明当前用的是 QtWebEngine 内核。': '<li><b>Message "HTML5 player not supported"</b>: this means the QtWebEngine engine is in use.',
    '<li><b>提示</b>：MHTML 由内核快照功能生成，最忠实还原页面。</li>': "<li><b>Tip</b>: MHTML is produced by the engine's snapshot feature and reproduces the page most faithfully.</li>",
    '<li><b>插件以外的功能都在菜单里</b>：文件（保存 / 打印）、工具（下载 / 历史 /': '<li><b>Everything except extensions lives in the menus</b>: File (save / print), Tools (downloads / history /',
    '<li><b>搜索</b>：顶部搜索框按标题或网址筛选，<b>命中的关键字会用荧光笔高亮显示</b>，': '<li><b>Search</b>: the box at the top filters by title or URL, and <b>matching keywords are highlighted like a marker pen</b>;',
    '<li><b>播放卡顿或黑屏</b>：可先用「工具 → Cookie 与缓存管理」清理缓存，': '<li><b>Stuttering or a black screen</b>: first clear the cache with "Tools → Cookie and cache management",',
    '<li><b>操作</b>：搜索、双击打开、删除单条、按时间范围清除、清空全部。</li>': '<li><b>Actions</b>: search, double-click to open, delete a single entry, clear by time range, clear all.</li>',
    '<li><b>效果</b>：浏览历史不写入磁盘；Cookie 与缓存仅保存在内存中，': '<li><b>Effect</b>: browsing history is not written to disk; Cookie and cache are kept in memory only',
    '<li><b>整理收藏夹</b>：<code>Ctrl+Shift+O</code>，支持上移 / 下移 / 改名 / 改地址 / 删除。</li>': '<li><b>Organize favorites</b>: <code>Ctrl+Shift+O</code>, supports move up / move down / rename / change address / delete.</li>',
    '<li><b>是否在后台被挂起</b>：后台标签页闲置较久会被挂起以省内存。': '<li><b>Whether it was suspended in the background</b>: background tabs left idle for a while are suspended to save memory.',
    '<li><b>是否是大会员内容</b>：会员专享清晰度 / 番剧需要相应权限。</li>': '<li><b>Whether it is premium member content</b>: member-only resolutions / anime require the matching entitlement.</li>',
    '<li><b>是否需要登录</b>：番剧、影视、1080P 以上清晰度、部分 UP 主视频': '<li><b>Whether sign-in is required</b>: anime, movies and TV, resolutions above 1080P, and some creator videos',
    '<li><b>标签页</b>：工具栏右侧 <code>+</code> 新建；页面里的': '<li><b>Tabs</b>: create a new one with <code>+</code> on the right of the toolbar; a',
    '<li><b>测试地址</b>：': '<li><b>Test address</b>:',
    '<li><b>深色 / 浅色</b>：同一位置切换，所有对话框（含设置页内的说明文字）': '<li><b>Dark / light</b>: switch in the same place; every dialog (including the explanatory text on settings pages)',
    '<li><b>添加</b>：<code>Ctrl+D</code> 或工具栏星标按钮，可修改名称与地址。</li>': '<li><b>Add</b>: <code>Ctrl+D</code> or the star button on the toolbar; the name and address can be changed.</li>',
    '<li><b>用途</b>：访问只为手机提供页面的站点、绕过某些客户端的 UA 限制等。': '<li><b>Uses</b>: visiting sites that only serve pages to phones, getting around the UA restrictions of some clients, and so on.',
    '<li><b>番剧 / 影视 / 1080P 以上清晰度播不了</b>：这些内容要求<b>先登录</b>': "<li><b>Anime / movies / anything above 1080P won't play</b>: this content requires you to <b>sign in first</b>",
    '<li><b>目录</b>：<b>第一次下载时</b>会让你选择保存目录，之后默认使用它；': '<li><b>Folder</b>: <b>on the first download</b> you pick a save folder, which is then used by default;',
    '<li><b>直接玩某个 Flash 游戏</b>：如果知道 .swf 地址，': '<li><b>Playing a Flash game directly</b>: if you know the .swf address,',
    '<li><b>相关的还有</b>：「帮助 → 视频播放自检」看解码能力，': '<li><b>Related</b>: "Help → Video playback self-check" for decoding capability,',
    '<li><b>磁盘缓存上限</b>：在「设置 → 性能」中设定（WebView2 以命令行开关生效，': '<li><b>Disk cache limit</b>: set in "Settings → Performance" (for WebView2 it takes effect as a command-line switch,',
    '<li><b>算法</b>：AES-256-GCM（带认证，防篡改），文件格式为': '<li><b>Algorithm</b>: AES-256-GCM (authenticated, tamper-proof); the file format is',
    '<li><b>系统原生窗口边框</b>：勾选后使用 Windows 自己的标题栏': "<li><b>Native system window frame</b>: when checked, Windows' own title bar is used",
    '<li><b>缓存</b>：显示磁盘缓存与用户配置目录的实际占用，': '<li><b>Cache</b>: shows the real disk usage of the disk cache and the user profile directory;',
    '<li><b>缩放</b>：<code>Ctrl+加号 / 减号 / 0</code>，状态栏右下角显示当前比例，': '<li><b>Zoom</b>: <code>Ctrl+plus / minus / 0</code>, with the current level shown at the bottom right of the status bar;',
    '<li><b>网络原因</b>：视频分片（.m4s）走的是独立 CDN，': '<li><b>Network causes</b>: video segments (.m4s) come from a separate CDN,',
    '<li><b>自动检测</b>：操作系统与位数、WebView2 运行时（读注册表，含用户级安装）、': '<li><b>Automatic check</b>: operating system and bitness, WebView2 runtime (read from the registry, including per-user installs),',
    '<li><b>自定义</b>：选择「自定义」后填入任意 UA；': '<li><b>Custom</b>: choose "Custom" and enter any UA;',
    '<li><b>自定义边框颜色</b>：勾选「自定义边框颜色」后选色，': '<li><b>Custom border color</b>: check "Custom border color" and pick a color;',
    '<li><b>自检工具</b>：菜单「帮助 → 视频播放自检」会打开一个页面，': '<li><b>Self-check tool</b>: the menu item "Help → Video playback self-check" opens a page',
    '<li><b>规则保存在哪</b>：数据目录下的 <code>adblock.json</code>，': '<li><b>Where rules are stored</b>: <code>adblock.json</code> in the data directory,',
    '<li><b>规则管理</b>：「工具 → 广告屏蔽规则」，': '<li><b>Rule management</b>: "Tools → Ad blocking rules",',
    '<li><b>解密工具</b>：菜单「工具 → 导出明文数据」把加密文件导出为 JSON，': '<li><b>Decryption tool</b>: the menu item "Tools → Export plaintext data" exports the encrypted files as JSON,',
    '<li><b>记录</b>：下载记录同样加密保存，可在下载窗口中清除。</li>': '<li><b>Record</b>: the download list is encrypted as well and can be cleared in the downloads window.</li>',
    '<li><b>设置</b>：菜单「设置 → 设置」，或工具栏齿轮按钮；': '<li><b>Settings</b>: menu "Settings → Settings", or the gear button on the toolbar;',
    '<li><b>证书校验</b>：证书异常（过期、名称不符、自签名等）时弹出详情对话框，': '<li><b>Certificate validation</b>: when a certificate is abnormal (expired, name mismatch, self-signed, and so on) a details dialog appears',
    '<li><b>诊断报告</b>：支持一键复制到剪贴板或保存为 txt，反馈问题时很有用。</li>': '<li><b>Diagnostic report</b>: can be copied to the clipboard or saved as a txt file with one click, which is very useful when reporting a problem.</li>',
    '<li><b>误拦截</b>：提示页上点「我了解风险，继续访问」可临时放行。</li>': '<li><b>False block</b>: click "I understand the risk, continue" on the warning page to allow it temporarily.</li>',
    '<li><b>运行状态</b>：「设置 → 性能」显示主进程内存、磁盘缓存、用户配置占用、': '<li><b>Status</b>: "Settings → Performance" shows main-process memory, disk cache, user profile usage,',
    '<li><b>连接状态指示</b>：地址栏左侧图标显示当前页面的<b>传输层</b>状态 ——': '<li><b>Connection status indicator</b>: the icon at the left of the address bar shows the <b>transport layer</b> status of the current page -',
    '<li><b>隐藏标签页停止渲染</b>：只显示当前标签页的内容，降低 CPU 占用。</li>': '<li><b>Stop rendering hidden tabs</b>: only the current tab is rendered, lowering CPU usage.</li>',
    '<li><b>需要 WebView2 内核</b>：QtWebEngine 无法把本地 Ruffle 提供给网页。</li>': '<li><b>Requires the WebView2 engine</b>: QtWebEngine cannot provide local Ruffle to pages.</li>',
    '<li><b>页面内查找</b>：<code>Ctrl+F</code> 打开查找栏，显示匹配数量，': '<li><b>Find in page</b>: <code>Ctrl+F</code> opens the find bar and shows the number of matches;',
    '<li><b>页面另存为</b>：<code>Ctrl+S</code>，可选三种格式 ——': '<li><b>Save page as</b>: <code>Ctrl+S</code>, with three formats to choose from -',
    '<li><b>预设</b>：一键切换常见浏览器与设备标识（Windows Chrome / Edge / Firefox、': '<li><b>Presets</b>: switch common browser and device identifiers with one click (Windows Chrome / Edge / Firefox,',
    '<li>技术栈：Python + PySide6（Qt 6）+ Edge WebView2 / QtWebEngine + pythonnet</li>': '<li>Tech stack: Python + PySide6 (Qt 6) + Edge WebView2 / QtWebEngine + pythonnet</li>',
    '<li>界面图标全部由代码绘制，不含任何第三方素材。</li>': '<li>All UI icons are drawn in code; no third-party assets are included.</li>',
    '<p><b>先说结论</b>：Adobe Flash Player 已经在 2020 年底停止支持，': '<p><b>The short answer first</b>: Adobe Flash Player reached end of support at the end of 2020,',
    '<p><b>如果个别视频仍然播不了</b>，请依次确认：</p>': '<p><b>If a few videos still will not play</b>, check the following in order:</p>',
    '<p><b>当前使用的是 QtWebEngine 内核</b>，它使用的是 Qt 官方的': "<p><b>The current engine is QtWebEngine</b>, which uses Qt's official",
    '<p><b>视频播不了？</b>先看「帮助 → 视频播放自检」，': '<p><b>Video won\'t play?</b> Start with "Help → Video playback self-check",',
    '<p><b>解决方法</b>：到微软官网下载并安装': "<p><b>How to fix</b>: download and install from Microsoft's website",
    '<p><b>解决方法</b>：打开「设置 → 外观 → 渲染引擎」，': '<p><b>How to fix</b>: open "Settings -> Appearance -> Rendering Engine",',
    '<p>下表由程序当前注册的快捷键自动生成，功能增删后会自动同步。</p>': '<p>The table below is generated automatically from the shortcuts currently registered by the program and stays in sync as features are added or removed.</p>',
    '<p>内置搜索引擎：{0}</p>': '<p>Built-in search engine: {0}</p>',
    '<p>内置预设：': '<p>Built-in presets: ',
    '<p>广告屏蔽分两部分：<b>自动拦截弹窗</b> 与 <b>手动标记要屏蔽的元素</b>。</p>': '<p>Ad blocking has two parts: <b>blocking popups automatically</b> and <b>marking elements to block by hand</b>.</p>',
    '<p>当前使用：<b>{0}</b></p>': '<p>Currently in use: <b>{0}</b></p>',
    '<p>当前内核支持 H.264 / AAC，可以正常播放哔哩哔哩等站点的 HTML5 视频。</p>': '<p>The current engine supports H.264 / AAC, so HTML5 video on sites like bilibili plays OK.</p>',
    '<p>当前是 Edge WebView2 内核，但检测到 <b>H.264 解码不可用</b>。': '<p>The current engine is Edge WebView2, but <b>H.264 decoding is not available</b>.',
    '<p>本帮助内容会随功能更新同步维护：快捷键、主题、引擎、UA 预设等': '<p>This help is maintained in step with feature updates: keyboard shortcuts, themes, engines, UA presets, and so on',
    '<p>本程序内置的是 GitHub 上开源的 <b>Ruffle</b>': '<p>What this program has built in is the open-source <b>Ruffle</b> from GitHub',
    '<p>程序依赖系统的 <b>Edge WebView2 运行时</b>渲染网页。若它缺失或损坏，': '<p>The program relies on the system <b>Edge WebView2 runtime</b> to render web pages. If it is missing or damaged,',
    '<p>程序内置两种内核，<b>只有 Edge WebView2 含 H.264/AAC 专有编解码器</b>，': '<p>The program has two engines built in, and <b>only Edge WebView2 includes the proprietary H.264/AAC codecs</b>,',
    '<p>设置项分布：</p>': '<p>Where the settings live:</p>',
    '<tr><td>AAC（audio/mp4; mp4a）</td><td id="aac">检测中…</td></tr>': '<tr><td>AAC (audio/mp4; mp4a)</td><td id="aac">Checking…</td></tr>',
    '<tr><td>AV1</td><td id="av1">检测中…</td></tr>': '<tr><td>AV1</td><td id="av1">Checking…</td></tr>',
    '<tr><td>H.264（video/mp4; avc1）</td><td id="h264">检测中…</td></tr>': '<tr><td>H.264 (video/mp4; avc1)</td><td id="h264">Checking…</td></tr>',
    '<tr><td>H.265（HEVC）</td><td id="h265">检测中…</td></tr>': '<tr><td>H.265 (HEVC)</td><td id="h265">Checking…</td></tr>',
    '<tr><td>MediaSource（MSE，流媒体必需）</td><td id="mse">检测中…</td></tr>': '<tr><td>MediaSource (MSE, required for streaming)</td><td id="mse">Checking…</td></tr>',
    '<tr><td>User-Agent</td><td id="ua">读取中…</td></tr>': '<tr><td>User-Agent</td><td id="ua">Reading…</td></tr>',
    '<tr><td>加密媒体（EME/Widevine）</td><td id="eme">检测中…</td></tr>': '<tr><td>Encrypted media (EME/Widevine)</td><td id="eme">Checking…</td></tr>',
    "<tr><th align='left'>快捷键</th><th align='left'>功能</th></tr>": "<tr><th align='left'>Shortcut</th><th align='left'>Function</th></tr>",
    'Android · 手机版': 'Android · Phone',
    'Chromium 内核（含本程序使用的 WebView2）从 88 版起': 'and Chromium-based engines (including the WebView2 this program uses) have, since version 88,',
    'Chromium 构建，<b>不含 H.264 / AAC 等专有编解码器</b>，': 'Chromium build and <b>does not include proprietary codecs such as H.264 / AAC</b>,',
    'Cookie 与缓存': 'Cookies and cache',
    'Cookie 与缓存 / 无痕 / 快捷方式）、帮助（帮助 / 视频自检）。</li>': 'Cookie and cache / incognito / shortcuts), Help (help / video self-check).</li>',
    'Cookie 与缓存由内核管理，可在此查看与清理。': 'Cookies and cache are managed by the engine and can be viewed and cleared here.',
    'Cookie 与缓存管理': 'Cookies and Cache',
    'Cookie 与缓存管理(K)...': 'Cookies and Cache(K)...',
    'Edge WebView2（Microsoft Edge 内核）': 'Edge WebView2 (Microsoft Edge engine)',
    'Flash 兼容需要 Edge WebView2 内核（当前是 QtWebEngine）': 'Flash compatibility requires the Edge WebView2 engine (currently QtWebEngine)',
    'Flash 兼容（Ruffle 无广告 Flash）、User-Agent 预设与自定义、HTTPS 证书校验方式、可疑网址提示与名单管理': 'Flash compatibility (Ruffle ad-free Flash), User-Agent presets and custom values, HTTPS certificate verification mode, suspicious site prompts and list management',
    'Flash 兼容（Ruffle）': 'Flash compatibility (Ruffle)',
    'Flash 兼容（Ruffle，无广告）': 'Flash compatibility (Ruffle, ad-free)',
    'Flash 兼容（Ruffle，无广告）(F)': 'Flash compatibility (Ruffle, ad-free)(F)',
    'Flash 小游戏（无广告）': 'Flash games (ad-free)',
    'H.264 / AAC / H.265 / AV1 的支持；': 'H.264 / AAC / H.265 / AV1;',
    'H.264 / AAC / MP3 等完整编解码器，可播放哔哩哔哩等站点': 'Full codecs such as H.264 / AAC / MP3; plays sites like Bilibili',
    'HTTP 未加密连接': 'HTTP unencrypted connection',
    'HTTP 版本不受支持': 'Unsupported HTTP version',
    'HTTPS 加密连接': 'HTTPS encrypted connection',
    'HTTPS 证书校验': 'HTTPS certificate verification',
    'IP 直连、非常规端口、punycode 同形异义域名、<code>@</code> 伪装、': 'direct IP access, unusual ports, punycode homograph domains, <code>@</code> disguise,',
    'MHTML 单文件 (*.mhtml)': 'MHTML single file (*.mhtml)',
    'MHTML 单文件 (*.mhtml);;完整网页 (*.htm *.html);;仅 HTML (*.html)': 'MHTML single file (*.mhtml);;Complete webpage (*.htm *.html);;HTML only (*.html)',
    'PDF 已生成：': 'PDF generated: ',
    'PDF 已生成：\n{0}': 'PDF created:\n{0}',
    'PDF 文件 (*.pdf)': 'PDF file (*.pdf)',
    'QtWebEngine {0}（Qt 自带内核）': 'QtWebEngine {0} (Qt built-in engine)',
    'QtWebEngine 内核会先生成打印预览 PDF 再交给系统阅读器。</li>': 'the QtWebEngine engine first generates a print-preview PDF and hands it to the system reader.</li>',
    'UI 风格(T)：': 'UI style(T): ',
    'UI 风格（XP/98/7/8.1/10）、深色浅色、自定义边框颜色、渲染引擎、工具栏、窗口边框': 'UI style (XP/98/7/8.1/10), light and dark themes, custom border colors, rendering engine, toolbar, window frame',
    'User-Agent（用户代理）': 'User-Agent',
    'WebView2 组件文件': 'WebView2 component files',
    'WebView2 运行时': 'WebView2 Runtime',
    'WebView2 运行环境自动诊断（系统 / 运行时 / 组件文件 / .NET / 数据目录），缺什么点一下就能下载安装': 'Automatic WebView2 environment diagnostics (system / runtime / component files / .NET / data folder). One click to download and install whatever is missing',
    'WebView2 运行环境自检与一键修复。': 'WebView2 runtime environment self-check with one-click repair.',
    'WebView2 需要 64 位 Windows 10 / 11。': 'WebView2 requires 64-bit Windows 10 / 11.',
    "badge.textContent = '⚠ 当前内核不支持 H.264，多数视频无法播放';": "badge.textContent = '⚠ The current engine does not support H.264; most videos cannot play';",
    'dns-prefetch / preconnect，加快点击后的打开速度；': 'dns-prefetch / preconnect on the domains of links in the current page, speeding up opening after a click;',
    'hops = 3;   // 点击时小猫连跳几下': 'hops = 3;   // how many jumps the kitten makes per click',
    'iPad · 平板版': 'iPad · Tablet',
    'iPhone · 手机版': 'iPhone · Phone',
    'lite browser 的数据已加密，请输入口令解锁：': 'lite browser data is encrypted. Enter your passphrase to unlock: ',
    'lite-browser-诊断报告.txt': 'lite-browser-diagnostic-report.txt',
    'macOS Safari、Linux、Android、iPhone、iPad、微信内置浏览器）。</li>': 'macOS Safari, Linux, Android, iPhone, iPad, WeChat built-in browser).</li>',
    'node.innerHTML = yes ? \'<span class="ok">支持</span>\'': 'node.innerHTML = yes ? \'<span class="ok">Supported</span>\'',
    'pythonnet / clr_loader / cffi 正常': 'pythonnet / clr_loader / cffi OK',
    '{0}\n点击查看详细信息': '{0}\nClick to view details',
    '{0} - {1}（作者 {2}）': '{0} - {1} (by {2})',
    '{0} v{1}\n作者：{2}\n点击查看「关于」': '{0} v{1}\nAuthor: {2}\nClick to view "About"',
    '{0} {1} 环境诊断报告': '{0} {1} environment diagnostic report',
    '{0} 使用帮助': '{0} Help',
    '{0} 环境自检': '{0} Environment Check',
    '{0}\u3000{1}\u3000{2} 位': '{0}\u3000{1}\u3000{2} digits',
    '{0}（{1} 位）': '{0} ({1} digits)',
    '{0}（访问 {1} 次）': '{0} ({1} visits)',
    '{0}，{1} MB（开源 Flash 模拟器，无广告）': '{0}, {1} MB (open-source Flash emulator, ad-free)',
    '“{0}”已经在收藏夹中，是否更新它的名称？': '"{0}" is already in your bookmarks. Update its name?',
    '⚠ 未找到内置的 Ruffle 文件（lib/ruffle），Flash 兼容不可用。': '⚠ Built-in Ruffle files not found (lib/ruffle). Flash compatibility is unavailable.',
    '✓ 已屏蔽该元素（规则已保存到 {0}）': '✓ Element blocked (rule saved to {0})',
    '\u3000内核 {0}': '\u3000Engine {0}',
    '「帮助 → 视频播放自检」会生成并打开这个页面，用来快速判断': '"Help -> Video Playback Self-Check" generates and opens this page so you can quickly tell',
    '「查看 → 深色模式」（<code>Ctrl+Shift+D</code>）快速切换。': '"View → Dark mode" (<code>Ctrl+Shift+D</code>) to switch quickly.',
    '「设置 → 内核与环境」里的诊断页用它检查：': 'The diagnostic page under "Settings -> Engine and Environment" uses it to check: ',
    '「设置 → 外观 → 渲染引擎」切换为 <b>Edge WebView2</b> 并重启即可。': '"Settings → Appearance → Rendering engine" and switch to <b>Edge WebView2</b>, then restart.',
    '「设置 → 外观 → 渲染引擎」切换内核。</li>': 'and "Settings → Appearance → Rendering engine" to switch engines.</li>',
    '一切正常，WebView2 环境可以正常使用': 'All good — the WebView2 environment is working normally',
    '一只路过的哈基米 🐱 帮你将「{0}」放在了：': 'A passing Hachimi 🐱 put "{0}" in:',
    '一只路过的哈基米 🐱 帮你将「{0}」放在了：\n{1}\n喵喵。': 'A passing Hachimi 🐱 put "{0}" in:\n{1}\nMeow.',
    '一只路过的哈基米 🐱 帮你记住了这个广告元素：': 'A passing Hachimi 🐱 remembered this ad element for you:',
    '一只路过的哈基米 🐱 帮你记住了这个广告元素：\n{0}\n以后打开 {1} 会自动隐藏它，喵喵。': 'A passing Hachimi 🐱 remembered this ad element for you:\n{0}\nNext time you open {1}, it will be hidden automatically. Meow.',
    '一键清理全部浏览数据（不会删除书签、历史与下载记录）。</li>': 'or clear all browsing data with one click (bookmarks, history, and download records are not deleted).</li>',
    '上一个': 'Previous',
    '上次启动耗时：<b>{0}</b><br>': 'Last startup time: <b>{0}</b><br>',
    '上移(U)': 'Move Up(U)',
    '下一个': 'Next',
    '下移(W)': 'Move Down(W)',
    '下载': 'Download',
    '下载失败': 'Download failed',
    '下载失败：{0}': 'Download failed: {0}',
    '下载失败：{0}\n\n是否改为打开官方下载页面手动安装？': 'Download failed: {0}\n\nOpen the official download page and install manually instead?',
    '下载完成': 'Download complete',
    '下载完成，正在启动安装程序…': 'Download complete. Starting the installer…',
    '下载并安装 WebView2 运行时(&D)': 'Download and install WebView2 Runtime(&D)',
    '下载的文件不完整': 'The downloaded file is incomplete',
    '下载目录(D)：': 'Download folder(D): ',
    '下载管理': 'Downloads',
    '下载管理(J)...': 'Downloads(J)...',
    '不受信任': 'Not trusted',
    '不可写：{0}': 'Not writable: {0}',
    '不可用：{0}': 'Unavailable: {0}',
    '不必自己去官网找。': 'so you do not have to hunt for it on the official website yourself.',
    '不支持（需要 Edge WebView2）': 'Not supported (requires Edge WebView2)',
    '不等同于恶意网址信誉数据库或杀毒软件。</li>': 'they are not the same as a malicious-URL reputation database or antivirus software.</li>',
    '两次输入的口令不一致。': 'The two passphrases do not match.',
    '严格模式：证书有问题时直接拒绝，不询问': 'Strict mode: reject outright when a certificate has problems, without asking',
    '中奖': 'Prize winner',
    '为了保证「随功能变动更新」，帮助里的**可变部分全部从程序本身读取**：': 'To keep it "up to date as features change", **all variable parts of this help are read from the program itself**:',
    '主域名中包含大量连字符': 'The main domain contains many hyphens',
    '主机名': 'Host name',
    '主页': 'Home page',
    '主页与启动方式、默认搜索引擎、下载目录、缩放比例': 'Home page and startup mode, default search engine, download folder, zoom level',
    '主页地址(H)：': 'Home page address(H): ',
    '主题与界面自定义': 'Theme and interface customization',
    '之后打开同一网站会自动隐藏它。</li>': 'The element is then hidden automatically the next time you open the same site.</li>',
    '也可以同时创建开始菜单快捷方式。</dd>': 'you can create a Start menu shortcut at the same time.</dd>',
    '也可以点「打开官方下载页」手动下载。</li>': 'or click "Open the official download page" to download it manually.</li>',
    '也可以点菜单「工具 → Flash 兼容」快速切换。</li>': 'or click the menu "Tools → Flash compatibility" to switch quickly.</li>',
    '也可以用菜单「帮助 → 视频播放自检」确认当前内核的解码能力。</dd>': 'You can also use the menu "Help → Video playback self-check" to confirm the current engine\'s decoding capability.</dd>',
    '也可在「设置 → 网络」打开<b>严格模式</b>直接拒绝。</li>': 'you can also turn on <b>strict mode</b> in "Settings → Network" to refuse outright.</li>',
    '也可在「设置 → 隐私与安全」中维护。</li>': 'you can also maintain it in "Settings → Privacy and security".</li>',
    '也可用源码目录里的 <code>tools\\decrypt_data.py</code>。</li>': 'or you can use <code>tools\\decrypt_data.py</code> in the source directory.</li>',
    '书签、历史记录与下载记录不会被删除。': 'Bookmarks, history, and download records will not be deleted.',
    '书签栏': 'Bookmarks bar',
    '书签栏(B)': 'Bookmarks bar (B)',
    '书签（收藏夹）': 'Bookmarks',
    '互操作组件': 'Interop components',
    '仅 HTML (*.html)': 'HTML only (*.html)',
    '仅含开源编解码器（VP8/VP9/AV1/Opus），不支持 H.264/AAC': 'Open-source codecs only (VP8/VP9/AV1/Opus), H.264/AAC not supported',
    '今天以前': 'Older than today',
    '从列表删除(D)': 'Remove from list (D)',
    '从微软官方下载 WebView2 引导安装器并运行（约 2 MB，需要联网）': 'Download the WebView2 bootstrapper from Microsoft and run it (about 2 MB, internet required)',
    '代理需要身份验证凭据': 'The proxy requires authentication credentials',
    '以后打开 {1} 会自动隐藏它，喵喵。': 'It will be hidden automatically from now on when you open {1}. Meow.',
    '会被内核挂起，释放渲染进程内存；切回该标签页时自动恢复，': 'are suspended by the engine to free renderer memory; switching back to the tab resumes them automatically,',
    '会话结束时': 'When the session ends',
    '传输加密：TLS 加密，证书校验由内核完成（仅代表传输层安全）': 'Transport encryption: TLS; certificate validation is handled by the engine (transport-layer security only)',
    '传输加密：无（内容可能在传输过程中被窃取或篡改）': 'Transport encryption: none (content may be intercepted or altered in transit)',
    '但复杂 3D、部分老旧加密游戏仍可能跑不起来，': 'but complex 3D and some old encrypted games may still fail to run;',
    '但官方二进制包只有开源编解码器，部分视频站点会提示不支持。</li>': 'but the official binaries include only open-source codecs, so some video sites report no support.</li>',
    '作者：{0}': 'Author: {0}',
    '作者：{2}': 'Author: {2}',
    '使用了非常规端口 {0}': 'Uses non-standard port {0}',
    '使用帮助(H)...': 'Help (H)...',
    '使用帮助：每项功能的作用与解释。': 'Help: what each feature does, explained.',
    '使用当前页(C)': 'Use current page (C)',
    '使用空白页(B)': 'Use blank page (B)',
    '使用系统原生窗口边框（经典 XP 外观请勿勾选）': 'Use native system window borders (leave unchecked for the classic XP look)',
    '使用默认页(D)': 'Use default page (D)',
    '保存为 MHTML 单文件(M)...': 'Save as MHTML single file (M)...',
    '保存为仅 HTML(S)...': 'Save as HTML only (S)...',
    '保存为完整网页(H)...': 'Save as complete webpage (H)...',
    '保存失败，请换个位置再试。': 'Save failed. Try another location.',
    '保存失败：当前内核不支持该操作。': 'Save failed: the current engine does not support this operation.',
    '保存网页': 'Save page',
    '保存诊断报告': 'Save diagnostic report',
    '保存诊断报告(&S)...': 'Save diagnostic report (&S)...',
    '保留时间(K)：': 'Keep for (K): ',
    '修改窗口边框样式需要重启 lite browser 才会生效。': 'Changing the window border style takes effect after you restart lite browser.',
    '停止': 'Stop',
    '全屏时自动隐藏所有工具栏，<code>Esc</code> 退出；网页内的 HTML5 全屏同样支持。</li>': 'in full screen all toolbars are hidden automatically and <code>Esc</code> exits; HTML5 full screen inside a page works too.</li>',
    '全屏显示(F)': 'Full screen (F)',
    '全选(A)': 'Select all (A)',
    '共 0 条': '0 items',
    '共 7 页：常规 / 外观 / 性能 / 网络 / 内核与环境 / 隐私与安全 / 关于。</li>': '7 pages in total: General / Appearance / Performance / Network / Engine and environment / Privacy and security / About.</li>',
    '共 {0} / {1} 条': '{0} / {1} items',
    '共 {0} 个匹配': '{0} matches',
    '共 {0} 条规则，覆盖 {1} 个网站': '{0} rules covering {1} sites',
    '共 {0} 条记录': '{0} records',
    '关于': 'About',
    '关于 {0}': 'About {0}',
    '关于 {0}(A)': 'About {0} (A)',
    '关于与版权': 'About and copyright',
    '关闭': 'Close',
    '关闭(C)': 'Close (C)',
    '关闭无痕浏览模式后将恢复记录浏览历史，切换模式会重新打开标签页，是否继续？': 'Turning off Incognito mode will resume recording browsing history, and switching modes will reopen tabs. Continue?',
    '关闭查找栏': 'Close find bar',
    '关闭标签页': 'Close tab',
    '关闭标签页(C)': 'Close tab (C)',
    '关闭程序后不保留。状态栏会显示红色的「无痕浏览」标识。</li>': 'and are gone once the program closes. The status bar shows a red "Incognito" badge.</li>',
    '关闭程序或切换模式后不会保留。切换模式会重新打开标签页。': 'and are not kept after you close the program or switch modes. Switching modes reopens the tabs.',
    '内存优化': 'Memory optimization',
    '内核(E)：': 'Engine (E): ',
    '内核与环境': 'Engine and environment',
    '内核与环境诊断': 'Engine and environment diagnostics',
    '内置版本：{0}\u3000体积：{1} MB': 'Bundled version: {0}  Size: {1} MB',
    '再刷新页面；也可以按 F12 打开开发者工具查看具体报错。</li>': 'then reload the page; you can also press F12 to open the developer tools and see the exact error.</li>',
    '准备清理…': 'Preparing to clean...',
    '切换模式会关闭当前所有标签页并重新打开，是否继续？': 'Switching modes closes all current tabs and reopens them. Continue?',
    '切换模式会重新打开标签页。</li>': 'Switching modes reopens the tabs.</li>',
    '创建开始菜单快捷方式(M)': 'Create Start menu shortcut (M)',
    '创建快捷方式失败：': 'Failed to create shortcut: ',
    '创建快捷方式失败：\n{0}': 'Failed to create the shortcut:\n{0}',
    '创建桌面快捷方式(S)': 'Create desktop shortcut (S)',
    '删除(D)': 'Delete (D)',
    '删除会话 Cookie(&S)': 'Delete session Cookies (&S)',
    '删除全部(&A)': 'Delete all (&A)',
    '删除所选(&D)': 'Delete selected (&D)',
    '到「设置 → 外观 → 渲染引擎」选择': 'Go to "Settings → Appearance → Rendering engine" and choose',
    '刷新': 'Refresh',
    '刷新统计(R)': 'Refresh statistics (R)',
    '前进': 'Forward',
    '剪切(T)': 'Cut (T)',
    '功能本身的文字说明集中在 :data:`SECTIONS`，随版本维护。': 'The descriptions of the features themselves live in :data:`SECTIONS` and are maintained with each release.',
    '功能说明(F)...': 'Features (F)...',
    '加密算法：AES-256-GCM': 'Encryption: AES-256-GCM',
    '加密算法：AES-256-GCM\n当前状态：{0}\n': 'Encryption: AES-256-GCM\nCurrent status: {0}\n',
    '加载网页图片（关闭可显著提速省流量）': 'Load page images (turn off for much faster loading and less data use)',
    '包括：Cookie、缓存、站点数据。': 'This includes: Cookies, cache, and site data.',
    '历史': 'History',
    '历史记录': 'History',
    '历史记录(H)...': 'History (H)...',
    '历史记录已清空。': 'History cleared.',
    '发现 ': 'Found ',
    '取消': 'Cancel',
    '取消下载(C)': 'Cancel download (C)',
    '取消口令': 'Remove password',
    '取消口令后，主密钥将改由 Windows 账户保护，是否继续？': 'After you remove the password, the master key will be protected by your Windows account instead. Continue?',
    '取消失败：{0}': 'Remove failed: {0}',
    '口令(P)：': 'Password (P): ',
    '口令不正确，请重试。': 'Incorrect password. Try again.',
    '口令不能为空。': 'Password cannot be empty.',
    '口令用于保护书签、历史记录与下载记录（AES-256-GCM）。': 'The password protects bookmarks, history and download records (AES-256-GCM).',
    '可上下跳转；<code>Esc</code> 关闭。</li>': 'you can jump up and down through them; <code>Esc</code> closes it.</li>',
    '可以指定浏览器启动时以及点击“主页”按钮时打开的页面：': 'Choose the page that opens when the browser starts and when you click "Home":',
    '可切换 {0} 种界面风格（': 'Switch between {0} UI styles (',
    '可在「工具 → Cookie 与缓存管理」里清理缓存后刷新页面重试。</li>': 'so clear the cache under "Tools -> Cookie and Cache Management", then refresh the page and try again.</li>',
    '可在「设置 → 外观 → 渲染引擎」中切换内核。': 'You can switch the engine in "Settings → Appearance → Rendering Engine".',
    '可在设置中设定默认值。</li>': 'you can set a default value in the settings.</li>',
    '可按关键字筛选，支持删除所选、删除全部、删除会话 Cookie。</li>': 'you can filter by keyword and delete the selection, delete all, or delete session Cookie.</li>',
    '可按网站查看、删除、清空，也可以点「打开该网站」回到那个页面。</li>': 'where you can view, delete, and clear rules by site, or click "Open this site" to go back to that page.</li>',
    '可清除缓存、清除站点数据（localStorage / IndexedDB）、': 'you can clear the cache, clear site data (localStorage / IndexedDB),',
    '可点「打开官方下载页」手动下载。': 'Click "Open Official Download Page" to download manually.',
    '可疑网址': 'Suspicious URL',
    '可疑网址名单': 'Suspicious URL list',
    '可疑网址拦截': 'Suspicious URL blocking',
    '可疑网址（本地规则命中）': 'Suspicious URL (matched a local rule)',
    '同一地址自动合并并显示访问次数。</li>': 'entries with the same address are merged and show a visit count.</li>',
    '名单文件位置：': 'List file location: ',
    '名单文件位置：\n{0}': 'List file location:\n{0}',
    '名称': 'Name',
    '名称(N)：': 'Name (N): ',
    '名称不匹配': 'Name does not match',
    '后台标签页挂起与等待时间、会话恢复、DNS 预解析、平滑滚动、图片加载、内存与缓存统计': 'Background tab suspension and wait time, session restore, DNS prefetch, smooth scrolling, image loading, memory and cache statistics',
    '后台标签页闲置后自动挂起（释放内存占用）': 'Automatically suspend idle background tabs (frees memory)',
    '后台标签页闲置后自动挂起（释放渲染进程内存）': 'Automatically suspend idle background tabs (frees renderer process memory)',
    '后退': 'Back',
    '含 H.264 / AAC 等完整编解码器，哔哩哔哩等站点可正常播放视频；</li>': 'with full codecs such as H.264 / AAC, so sites like Bilibili can play video normally;</li>',
    '启动与加载': 'Startup and loading',
    '启动时': 'On startup',
    '启动时恢复上次关闭时的标签页': 'Restore tabs from the last session on startup',
    '启用 Flash 兼容：用小游戏/动画网站需要的 Flash 运行时': 'Enable Flash compatibility: use the Flash runtime required by game and animation sites',
    '启用可疑网址拦截（黑名单 + 本地启发式规则）': 'Enable suspicious URL blocking (blacklist + local heuristic rules)',
    '启用无痕浏览模式（不记录历史、Cookie 与缓存）': 'Enable Incognito mode (no history, Cookies or cache recorded)',
    '命中黑名单的网址会被直接拦截并显示警告页；白名单中的域名永远不会被拦截（包括启发式规则）。': 'URLs on the blacklist are blocked immediately with a warning page; domains on the whitelist are never blocked (heuristic rules included).',
    '命中黑名单的网址会被直接拦截并显示警告页；白名单中的域名永远不会被拦截（包括启发式规则）。\n规则支持 example.com 与 *.example.com 两种写法。': 'URLs on the blocklist are blocked directly and show a warning page; domains on the allowlist are never blocked (heuristic rules included).\nRules support both example.com and *.example.com.',
    '哔哩哔哩等站点依赖它们才能播放。</p>': 'which sites like Bilibili need in order to play.</p>',
    '哔哩哔哩账号，未登录时页面会显示「出错啦」或要求登录，属于站点限制。</li>': 'to a Bilibili account; when you are not signed in the page shows "something went wrong" or asks you to log in, which is a site restriction.</li>',
    '喵喵。': 'Meow.',
    '因此哔哩哔哩等站点会提示「您当前的浏览器不支持 HTML5 播放器」。</p>': 'so sites like bilibili report "your current browser does not support the HTML5 player".</p>',
    '因此在「设置 → 性能」里默认是关闭的。</li>': 'so it is off by default in "Settings → Performance".</li>',
    '因法律原因不可用': 'Unavailable for legal reasons',
    '在此页上查找(F)': 'Find on this page (F)',
    '地址': 'Address',
    '地址(U)：': 'Address(U): ',
    '地址栏搜索': 'Search in the address bar',
    '域名': 'Domain',
    '域名中包含大量转义字符': 'Domain contains many escape characters',
    '域名包含 punycode（可能是同形异义钓鱼域名）': 'Domain contains punycode (possible homograph phishing domain)',
    '域名（例如 bad-site.com 或 *.bad-site.com）：': 'Domain (for example bad-site.com or *.bad-site.com): ',
    '基本可用，但有需要注意的项目': 'Basically usable, with items that need attention',
    '备注': 'Notes',
    '复制(C)': 'Copy(C)',
    '复制诊断报告(&C)': 'Copy diagnostics report(&C)',
    '外观': 'Appearance',
    '大小': 'Size',
    '失败': 'Failed',
    '如仍遇到播放中断，可在「设置 → 性能」关闭「后台标签页自动挂起」。</li>': 'if playback still stops, turn off "Automatically suspend background tabs" under "Settings -> Performance".</li>',
    '如果网页打不开，可以把这份报告发给作者排查。': 'If a page will not open, send this report to the author for troubleshooting.',
    '如果选择器太通用（会命中很多元素），': 'if the selector is too generic (it would match many elements),',
    '如需完全关闭，可在「设置 → 性能」里取消勾选自动挂起。</li>': 'to turn it off completely, uncheck auto-suspend in "Settings → Performance".</li>',
    '子域名层级过多（{0} 级），可能是随机生成的域名': 'Too many subdomain levels ({0}), possibly a randomly generated domain',
    '它会直接告诉你当前内核支不支持 H.264。</p>': 'which tells you straight away whether the current engine supports H.264.</p>',
    '它的广告也无法通过安装插件的方式去掉。</p>': 'and its ads cannot be removed by installing a plugin either.</p>',
    '它能在现代内核里直接运行 Flash 内容，<b>完全没有广告</b>，': 'It can run Flash content directly in modern engines with <b>no ads at all</b>,',
    '安全': 'Security',
    '安全：证书校验与可疑网址提示': 'Security: certificate validation and suspicious site warnings',
    '安装过程由微软的安装程序完成，可能需要管理员确认。是否继续？': "The installation is performed by Microsoft's installer and may require administrator confirmation. Continue?",
    '完成': 'Done',
    '完整': 'Full',
    '完整网页 (*.htm *.html)': 'Complete webpage (*.htm *.html)',
    '定位地址栏': 'Focus address bar',
    '实际大小(R)': 'Actual size(R)',
    '客户端证书有错误': 'Client certificate error',
    '客户端错误 {0}': 'Client error {0}',
    '密码': 'Password',
    '导出为 PDF': 'Export as PDF',
    '导出为 PDF(D)...': 'Export as PDF(D)...',
    '导出失败：当前内核不支持该操作。': 'Export failed: the current engine does not support this operation.',
    '导出失败：无法访问主窗口。': 'Export failed: cannot access the main window.',
    '导出明文数据(E)...': 'Export plaintext data(E)...',
    '导出明文数据到': 'Export plaintext data to',
    '将从微软官方下载 WebView2 引导安装器（约 2 MB）并运行。': 'The WebView2 bootstrapper (about 2 MB) will be downloaded from Microsoft and run.',
    '将从微软官方下载 WebView2 引导安装器（约 2 MB）并运行。\n\n安装过程由微软的安装程序完成，可能需要管理员确认。是否继续？': "The WebView2 bootstrapper installer (about 2 MB) will be downloaded from Microsoft and run.\n\nThe installation is performed by Microsoft's installer and may require administrator confirmation. Continue?",
    '尚未': 'Not yet',
    '尚未打开网页': 'No page open yet',
    '就收到 DNS 查询或连接，相当于提前暴露"你访问过当前页面"，': 'receive a DNS query or connection before you actually click, effectively revealing in advance that "you have visited the current page",',
    '就绪': 'Ready',
    '工具(T)': 'Tools(T)',
    '工具栏': 'Toolbar',
    '已保存到：': 'Saved to: ',
    '已保存到：\n{0}': 'Saved to:\n{0}',
    '已关闭 Flash 兼容': 'Flash compatibility turned off',
    '已切换到浅色模式': 'Switched to light mode',
    '已切换到深色模式': 'Switched to dark mode',
    '已加入屏蔽规则': 'Added to block rules',
    '已取消': 'Canceled',
    '已启动 WebView2 安装程序。': 'The WebView2 installer has been started.',
    '已启动 WebView2 安装程序。\n\n请按微软的安装向导完成安装（可能需要管理员确认），完成后回到这里点「重新检测」。': 'The WebView2 installer has started.\n\nFollow Microsoft\'s setup wizard to finish the installation (administrator confirmation may be required), then come back here and click "Check again".',
    '已启用口令保护，下次启动需要输入口令。': 'Passphrase protection is enabled; a passphrase will be required on the next start.',
    '已在开始菜单创建快捷方式：': 'Shortcut created in the Start menu: ',
    '已在桌面创建快捷方式：': 'Shortcut created on the desktop: ',
    '已安装 {0}（{1}）': 'Installed {0} ({1})',
    '已完成': 'Completed',
    '已导出 PDF：': 'PDF exported: ',
    '已导出 PDF：\n{0}': 'PDF exported:\n{0}',
    '已导出 {0} 个文件到：': 'Exported {0} files to: ',
    '已导出 {0} 个文件到：\n{1}': 'Exported {0} files to:\n{1}',
    '已开启 Flash 兼容（Ruffle，无广告），刷新页面生效': 'Flash compatibility enabled (Ruffle, ad-free); refresh the page to apply',
    '已拦截网页自动弹窗{0}（本次已拦 {1} 个）': 'Blocked automatic pop-ups{0} ({1} blocked this time)',
    '已拦截：该网址命中本地可疑规则': 'Blocked: this URL matched a local suspicious rule',
    '已挂起 {0} 个后台标签页，切回时自动恢复。': 'Suspended {0} background tabs; they resume automatically when you switch back.',
    '已暂停打开该网址（命中本地可疑规则）': 'Paused opening this URL (matched a local suspicious rule)',
    '已清除 {0} 条历史记录。': 'Cleared {0} history entries.',
    '已清除全部 Cookie。': 'Cleared all cookies.',
    '已清除全部浏览数据。': 'Cleared all browsing data.',
    '已清除磁盘缓存。': 'Cleared the disk cache.',
    '已清除站点数据。': 'Cleared site data.',
    '已清除缓存。': 'Cleared the cache.',
    '已生成打印预览 PDF，正在打开…': 'Print preview PDF generated, opening...',
    '帮助(H)': 'Help(H)',
    '常见问题': 'FAQ',
    '常见问题(Q)...': 'FAQ(Q)...',
    '常规': 'General',
    '并且会让网页以为自己装了 Flash。</p>': 'and makes pages believe Flash is installed.</p>',
    '并播放一段测试视频。</li>': 'and plays a test video.</li>',
    '并自动把页面里指向 .swf 的地址改成由本程序代取': 'and automatically rewrites addresses in the page that point to .swf so this program fetches them instead',
    '广告与弹窗拦截': 'Ad and pop-up blocking',
    '广告与弹窗拦截、无痕浏览、历史记录与保留天数、数据加密与口令、Cookie 与缓存清理': 'Ad and pop-up blocking, incognito browsing, history and retention days, data encryption and passphrase, cookie and cache cleanup',
    '广告屏蔽规则': 'Ad block rules',
    '广告屏蔽规则(&R)...': 'Ad block rules(&R)...',
    '广告屏蔽规则(R)...': 'Ad block rules(R)...',
    '广告标记失败：网页地址无效': 'Ad marking failed: invalid page address',
    '广告标记模式：点一下要屏蔽的广告，按 Esc 取消': 'Ad marking mode: click the ad you want to block, press Esc to cancel',
    '应用(A)': 'Apply(A)',
    '开发者工具(D)': 'Developer tools(D)',
    '开启后：浏览历史不写入磁盘，Cookie / 缓存仅保存在内存中，': 'When enabled: browsing history is not written to disk, cookies / cache are kept in memory only,',
    '开启后：浏览历史不写入磁盘，Cookie / 缓存仅保存在内存中，\n关闭程序或切换模式后不会保留。切换模式会重新打开标签页。': 'When enabled: browsing history is not written to disk, and cookies / cache are kept in memory only.\nNothing is kept after you close the program or switch modes. Switching modes reopens your tabs.',
    '开启平滑滚动': 'Enable smooth scrolling',
    '开启无痕浏览模式后，浏览历史不会被记录，Cookie 与缓存只保存在内存中。': 'In incognito mode, browsing history is not recorded and cookies and cache are kept in memory only.',
    '开启无痕浏览模式后，浏览历史不会被记录，Cookie 与缓存只保存在内存中。\n切换模式会关闭当前所有标签页并重新打开，是否继续？': 'In Incognito mode, browsing history is not recorded, and cookies and cache are kept in memory only.\nSwitching modes closes all current tabs and reopens them. Continue?',
    '开始时间': 'Start time',
    '异常': 'Error',
    '当前为关闭状态：遇到 Flash 网站会提示需要安装 Flash。': 'Currently off: Flash sites will prompt that Flash is required.',
    '当前为开启状态：网页里的 Flash 会自动用 Ruffle 运行。': 'Currently on: Flash content on web pages runs automatically with Ruffle.',
    '当前使用 QtWebEngine，无法把本地 Ruffle 提供给网页；请到「外观 → 渲染引擎」切换为 Edge WebView2 后重启。': 'QtWebEngine is currently in use and cannot provide the local Ruffle to web pages; switch to Edge WebView2 in "Appearance -> Rendering engine" and restart.',
    '当前使用内核默认 UA：': 'Currently using the engine default UA: ',
    '当前内核能不能播放 HTML5 视频（尤其是哔哩哔哩这类需要 H.264/AAC 的站点）：': 'whether the current engine can play HTML5 video (especially sites like bilibili that need H.264/AAC): ',
    '当前内核：{0}': 'Current engine: {0}',
    '当前处于无痕浏览模式': 'Currently in incognito mode',
    '当前处于无痕浏览模式：不记录历史、Cookie 与缓存': 'Currently in incognito mode: no history, cookies or cache are recorded',
    '当前将使用自定义 UA：': 'Currently using a custom UA: ',
    '当前引擎：{0}': 'Current engine: {0}',
    '当前引擎：{0}\n视频解码：{1}': 'Current engine: {0}\nVideo decoding: {1}',
    '当前渲染内核': 'Current rendering engine',
    '当前渲染引擎': 'Current rendering engine',
    '当前状态：{0}': 'Current status: {0}',
    '当前环境无法启用数据加密': 'Data encryption cannot be enabled in the current environment',
    '当前用户': 'Current user',
    '当前页面没有可以收藏的地址。': 'The current page has no address that can be bookmarked.',
    '待加载': 'Loading',
    '微信内置浏览器': 'WeChat built-in browser',
    '快捷方式已存在：': 'Shortcut already exists: ',
    '快捷方式已存在：\n{0}\n\n是否覆盖？': 'The shortcut already exists:\n{0}\n\nOverwrite it?',
    '快捷键一览': 'Keyboard shortcuts',
    '快捷键一览(K)...': 'Keyboard shortcuts(K)...',
    '快速上手': 'Quick Start',
    '性能': 'Performance',
    '性能与内存优化': 'Performance and Memory Optimization',
    '或「设置 → 隐私与安全 → Cookie 与缓存」。</li>': 'or "Settings → Privacy and security → Cookie and cache".</li>',
    '或「设置 → 隐私与安全」。</li>': 'or "Settings → Privacy and security".</li>',
    '或先用「导出明文数据」导出 JSON。</dd>': 'or export JSON first with "Export plaintext data".</dd>',
    '或直接修复 / 重装 Microsoft Edge，然后重启程序。</p>': 'or repair / reinstall Microsoft Edge directly, and then restart the program.</p>',
    '打印(P)...': 'Print(P)...',
    '打开 Flash 小游戏测试(&T)': 'Open Flash Game Test(&T)',
    '打开(O)': 'Open(O)',
    '打开上次关闭时的页面': 'Open pages from last session',
    '打开主页': 'Open Home Page',
    '打开名单文件(F)': 'Open List File(F)',
    '打开官方下载页(&P)': 'Open Official Download Page(&P)',
    '打开所在文件夹(F)': 'Open Containing Folder(F)',
    '打开目录(O)': 'Open Folder(O)',
    '打开空白页': 'Open Blank Page',
    '打开该网站(&O)': 'Open This Site(&O)',
    '找不到匹配项': 'No matches found',
    '找不到页面': 'Page not found',
    '报告已保存：{0}': 'Report saved: {0}',
    '拒绝访问': 'Access denied',
    '拦截网页自动弹出的窗口（非用户点击触发）': 'Block pop-up windows opened automatically (not triggered by user clicks)',
    '挂起后内核会释放该标签页的渲染进程与内存，切回该标签页时自动恢复，页面状态（滚动位置、表单内容）不会丢失。': "When suspended, the engine releases the tab's renderer process and memory, and restores it automatically when you switch back. Page state (scroll position, form contents) is preserved.",
    '按 F11 或 Esc 退出全屏': 'Press F11 or Esc to exit full screen',
    '按时间清除：': 'Clear by time: ',
    '按标题或网址筛选': 'Filter by title or URL',
    '提示：按 F1 可随时打开本帮助': 'Tip: press F1 to open this help at any time',
    '搜索(S)：': 'Search(S): ',
    '撤销(U)': 'Undo(U)',
    '操作已取消': 'Operation canceled',
    '操作系统': 'Operating system',
    '支付': 'Payment',
    '支持': 'Support',
    '支持中文与网址片段。</li>': 'Chinese text and URL fragments are both supported.</li>',
    '支持打开文件、打开所在文件夹、取消、删除、清除已完成。</li>': 'supports opening the file, opening the containing folder, cancel, delete, and clear completed.</li>',
    '收藏': 'Favorite',
    '收藏(A)': 'Favorite(A)',
    '收藏夹': 'Favorites',
    '收藏夹中的书签：': 'Bookmarks in Favorites: ',
    '收藏夹列表': 'Favorites list',
    '放大(I)': 'Zoom In(I)',
    '敏感词 + 非 HTTPS、高风险域名后缀、子域名层级过多、网址异常冗长等。': 'sensitive words + non-HTTPS, high-risk domain suffixes, too many subdomain levels, unusually long URLs, and so on.',
    '数据加密': 'Data Encryption',
    '数据加密与解密': 'Data Encryption and Decryption',
    '整理...': 'Organize...',
    '整理收藏夹': 'Organize Favorites',
    '整理收藏夹(O)...': 'Organize Favorites(O)...',
    '文件(F)': 'File(F)',
    '文件名': 'File name',
    '文本文件 (*.txt)': 'Text files (*.txt)',
    '新建标签页': 'New Tab',
    '新建标签页 (Ctrl+T)': 'New Tab (Ctrl+T)',
    '新建标签页(T)': 'New Tab(T)',
    '新标签页': 'New Tab',
    '方法不被允许': 'Method not allowed',
    '无人操作则 5 秒后自动消失；点气泡本体可直接打开所在文件夹。</li>': 'with no interaction it disappears after 5 seconds; click the bubble itself to open the containing folder.</li>',
    '无效': 'Invalid',
    '无法启动安装程序：{0}': 'Cannot start the installer: {0}',
    '无法启动安装程序：{0}\n\n可点「打开官方下载页」手动下载。': 'Could not start the installer: {0}\n\nYou can click "Open official download page" to download it manually.',
    '无法建立连接': 'Cannot establish a connection',
    '无法打开该网页': 'Cannot open this webpage',
    '无法打开该页面': 'Cannot open this page',
    '无法统计缓存占用。': 'Cannot calculate cache usage.',
    '无法解析域名': 'Cannot resolve the domain name',
    '无法访问服务器': 'Cannot reach the server',
    '无法访问此页面': 'This page cannot be reached',
    '无痕': 'Incognito',
    '无痕浏览': 'Incognito',
    '无痕浏览模式(N)': 'Incognito Mode(N)',
    '时间': 'Time',
    '明文 JSON，方便你自己备份或手工编辑。</li>': 'plain-text JSON, so you can back it up or edit it by hand.</li>',
    '明暗模式(M)：': 'Light/Dark Mode(M): ',
    '是': 'Yes',
    '是否改为打开官方下载页面手动安装？': 'Open the official download page to install manually instead?',
    '是否覆盖？': 'Overwrite?',
    '显示书签栏': 'Show bookmarks bar',
    '显示状态栏': 'Show status bar',
    '显示访问的网站、问题、颁发给、颁发者与有效期，由你决定是否继续；': 'showing the site visited, the problem, issued to, issuer, and validity period, and you decide whether to continue;',
    '更改(C)...': 'Change(C)...',
    '更新': 'Update',
    '最大化(X)': 'Maximize(X)',
    '最小化(N)': 'Minimize(N)',
    '最近 1 小时以前': 'Older than the last hour',
    '最近 30 天以前': 'Older than the last 30 days',
    '最近 7 天以前': 'Older than the last 7 days',
    '服务器不支持该请求': 'The server does not support this request',
    '服务器内部错误': 'Internal server error',
    '服务器返回无效响应': 'The server returned an invalid response',
    '服务器返回未知错误': 'The server returned an unknown error',
    '服务器错误 {0}': 'Server error {0}',
    '服务暂时不可用': 'Service temporarily unavailable',
    '未找到 lib/ruffle 文件': 'lib/ruffle files not found',
    '未检测到': 'Not detected',
    '未检测到 .NET Framework 与 .NET': '.NET Framework and .NET not detected',
    '未登录时会提示"先登录，再游戏"，这是站点要求，不是浏览器问题。</li>': 'and without signing in it says "log in first, then play", which is a site requirement, not a browser problem.</li>',
    '未知': 'Unknown',
    '未知错误': 'Unknown error',
    '未能生成选择器，广告标记已取消': 'Could not generate a selector; ad marking canceled',
    '未能解锁加密数据，本次运行不会保存书签、历史记录与下载记录。': 'Could not unlock encrypted data. Bookmarks, history, and download records will not be saved in this session.',
    '本地页面': 'Local page',
    '本检测基于本地启发式规则，仅用于识别可疑 URL 特征，不等同于恶意网址信誉数据库或杀毒软件。': 'This check uses local heuristic rules only to identify suspicious URL patterns; it is not a malicious-URL reputation database or antivirus software.',
    '本程序使用 Python + PySide6 编写。': 'This program is written in Python + PySide6.',
    '本程序使用 Python + PySide6 编写。\n可在「设置 → 外观 → 渲染引擎」中切换内核。': 'This program is written in Python + PySide6.\nYou can switch the engine under "Settings → Appearance → Rendering engine".',
    '查找：': 'Find: ',
    '查看(V)': 'View(V)',
    '查看源代码(C)': 'View Source(C)',
    '标准按钮': 'Standard Buttons',
    '标签页与导航': 'Tabs and Navigation',
    '标签页数与挂起数量，以及上次启动耗时；可一键挂起后台标签页或清理缓存。</li>': 'tab count and suspended count, and the last startup time; you can suspend background tabs or clear the cache with one click.</li>',
    '标记并屏蔽广告元素(M)': 'Mark and Block Ad Elements(M)',
    '标题': 'Title',
    '标题栏与窗口边框会一起使用该颜色；点「用主题默认值」恢复。</li>': 'the title bar and window border both use it; click "Use theme default" to restore.</li>',
    '检测到缺失时可一键下载并运行微软官方的 **WebView2 引导安装器**，': "If something is Missing, it can download and run Microsoft's official **WebView2 Bootstrapper** in one click,",
    '检测项目': 'Check Items',
    '正在下载': 'Downloading',
    '正在下载…': 'Downloading…',
    '正在下载… {0:.1f} / {1:.1f} MB': 'Downloading… {0:.1f} / {1:.1f} MB',
    '正在下载… {0} KB': 'Downloading… {0} KB',
    '正在准备渲染引擎…': 'Preparing rendering engine…',
    '正在准备界面…': 'Preparing interface…',
    '正在启动…': 'Starting…',
    '正在启动渲染引擎…': 'Starting rendering engine…',
    '正在打开网页...': 'Opening webpage...',
    '正在打开首页…': 'Opening home page…',
    '正在播放音频/视频的标签页已自动跳过挂起；': 'Tabs that are playing audio/video already skip suspension automatically;',
    '正在播放音频或视频的标签页<b>会自动跳过挂起</b>；': 'Tabs that are playing audio or video <b>skip suspension automatically</b>;',
    '正在检测…': 'Checking…',
    '正在统计…': 'Calculating...',
    '正在解锁数据…': 'Unlocking data...',
    '正在读取…': 'Loading...',
    '正在读取书签与历史…': 'Loading bookmarks and history...',
    '正常': 'OK',
    '此网站的安全证书有问题': "There is a problem with this website's security certificate",
    '每次下载都询问保存位置': 'Ask where to save each download',
    '每行一个域名，<code>#</code> 注释，<code>!</code> 开头为白名单；': 'one domain per line, <code>#</code> for comments, a leading <code>!</code> for the allowlist;',
    '每项都给出「正常 / 注意 / 异常」与处理建议。</li>': 'each item gets "OK / Warning / Error" plus a suggested fix.</li>',
    '永久保留': 'Keep forever',
    '没有可用的标签页': 'No tabs available',
    '注意': 'Warning',
    '注意：HTTPS 只说明"连接经过 TLS 加密且证书验证通过"，': 'Note: HTTPS only means that "the connection is TLS-encrypted and the certificate was verified";',
    '浅色': 'Light',
    '浅色 / 深色模式切换（会记住选择）': 'Switch between light / dark mode (your choice is remembered)',
    '浏览(B)...': 'Browse(B)...',
    '浏览历史': 'Browsing history',
    '涉及文件：data\\bookmarks.dat、history.dat、downloads.dat': 'Files involved: data\\bookmarks.dat, history.dat, downloads.dat',
    '深色': 'Dark',
    '深色模式(D)': 'Dark mode(D)',
    '添加(&A)...': 'Add(&A)...',
    '添加(&D)...': 'Add(&D)...',
    '添加...': 'Add...',
    '添加到收藏夹(A)...': 'Add to Favorites(A)...',
    '添加域名': 'Add domain',
    '添加收藏': 'Add bookmark',
    '添加时间': 'Date added',
    '清理 localStorage、IndexedDB 等站点存储': 'Clear site storage such as localStorage and IndexedDB',
    '清理缓存(C)': 'Clear cache(C)',
    '清空全部(&C)': 'Clear all(&C)',
    '清空全部(L)': 'Clear all(L)',
    '清除(G)': 'Clear(G)',
    '清除全部浏览数据(&A)': 'Clear all browsing data(&A)',
    '清除已完成': 'Clear completed',
    '清除站点数据(&L)': 'Clear site data(&L)',
    '清除缓存(&C)': 'Clear cache(&C)',
    '渲染引擎说明': 'Rendering engine',
    '渲染引擎（切换后需重启程序）': 'Rendering engine (restart required after switching)',
    '滚动位置与表单内容不会丢失。</li>': 'and scroll position and form contents are not lost.</li>',
    '点「开始游戏」即可；注意 4399 有<b>健康系统</b>，': 'just click "Start game"; note that 4399 has a <b>health system</b>,',
    '点一下网页上要屏蔽的广告（弹窗、横幅、浮层），以后打开同一网站自动隐藏': 'Click an ad on the page (pop-up, banner, overlay) to hide it automatically on this site from now on',
    '点击下方「下载并安装 WebView2 运行时」，按提示完成后重新检测。': 'Click "Download and install WebView2 Runtime" below, then check again when the installer finishes.',
    '点击切换到无痕浏览模式': 'Click to switch to incognito mode',
    '点击查看「关于」': 'Click to view "About"',
    '点击查看详细信息': 'Click to view details',
    '点击页面里的「开始游戏」即可。': 'Click "Start Game" on the page.',
    '点右上角 × 可立即关闭；鼠标停在上面时不会消失，移开后 2 秒自动关闭，': 'click the × at its top right to close it immediately; it stays while the pointer is over it and closes 2 seconds after the pointer leaves;',
    '版本 {0}    作者：{1}': 'Version {0}    Author: {1}',
    '版本 {0}  （Chromium 内核）': 'Version {0}  (Chromium engine)',
    '版本、作者、当前渲染引擎与解码能力': 'Version, author, current rendering engine, and decoding capabilities',
    '状态': 'Status',
    '状态栏(S)': 'Status bar(S)',
    '状态栏会提示拦截数量；你自己点击链接打开的新标签页不受影响。</li>': 'and the status bar shows the blocked count; new tabs you open yourself by clicking a link are unaffected.</li>',
    '环境自检完成，报告已保存到：': 'Self-check complete. Report saved to: ',
    '环境自检完成，报告已保存到：\n{0}\n\n如果网页打不开，可以把这份报告发给作者排查。': 'Environment check complete. The report was saved to:\n{0}\n\nIf web pages will not open, you can send this report to the author for troubleshooting.',
    '生成 PDF 失败。': 'Failed to generate PDF.',
    '用主题默认值': 'Use theme default',
    '用开源 Ruffle 模拟器运行 Flash 内容（4399 小游戏等），无广告、无需装 Flash 插件': 'Run Flash content with the open-source Ruffle emulator (4399 mini games, etc.), ad-free and no Flash plug-in needed',
    '用户数据目录': 'User data folder',
    '界面下方会实时显示当前生效的 UA 字符串。</li>': 'The UA string currently in effect is shown live below the field.</li>',
    '界面风格': 'UI style',
    '留空表示使用内核默认 User-Agent': 'Leave blank to use the engine default User-Agent',
    '登录': 'login',
    '白名单（放行）': 'Whitelist (allow)',
    '直接从程序读取，功能说明随版本修订。</p>': 'are read directly from the program, and feature descriptions are revised with each version.</p>',
    '直接使用 IP 地址访问，而非域名': 'Accessed by IP address instead of a domain name',
    '直接列出当前内核、WebView2 版本、H.264/AAC/H.265/AV1 支持情况，': 'listing the current engine, WebView2 version, and H.264/AAC/H.265/AV1 support,',
    '直接粘到地址栏回车，程序会用内置播放器打开它。</li>': 'paste it into the address bar and press Enter; the program opens it in its built-in player.</li>',
    '确定': 'OK',
    '确定删除全部 Cookie 吗？所有网站的登录状态都会失效。': 'Delete all Cookies? You will be signed out of every website.',
    '确定删除选中的 {0} 条 Cookie 吗？': 'Delete the selected {0} Cookies?',
    '确定后重启程序即可。</p>': 'confirm, and then restart the program.</p>',
    '确定清除全部 Cookie 吗？所有网站的登录状态都会失效。': 'Clear all Cookies? You will be signed out of every website.',
    '确定清除全部浏览数据吗？': 'Clear all browsing data?',
    '确定清除全部浏览数据吗？\n\n包括：Cookie、缓存、站点数据。\n书签、历史记录与下载记录不会被删除。': 'Clear all browsing data?\n\nThis includes: cookies, cache and site data.\nBookmarks, history and download records will not be deleted.',
    '确定清除站点数据（localStorage / IndexedDB 等）吗？': 'Clear site data (localStorage / IndexedDB, etc.)?',
    '确定要删除书签“{0}”吗？': 'Delete bookmark "{0}"?',
    '确定要清空全部 {0} 条广告屏蔽规则吗？': 'Clear all {0} ad blocking rules?',
    '确定要清空全部历史记录吗？': 'Clear all history?',
    '确定要继续访问吗？': 'Continue anyway?',
    '确定要继续访问吗？\n\n继续访问会让本次连接失去证书保护，请不要在该网站输入密码或支付信息。': 'Continue to the site?\n\nContinuing will leave this connection without certificate protection. Do not enter passwords or payment information on this site.',
    '确认口令(C)：': 'Confirm passphrase(C): ',
    '移除(&M)': 'Remove(&M)',
    '移除(&R)': 'Remove(&R)',
    '程序不打开界面，会直接把报告保存到数据目录的': 'the program opens no window and saves the report straight to the data directory as',
    '程序会回退到 .NET 运行时；如异常可修复系统组件。': 'The app will fall back to the .NET runtime; if problems occur, repair the system components.',
    '程序会自动退化为更精确的写法，误伤正常内容的可能性很低。</li>': 'the program falls back to a more precise form, so the chance of catching normal content is very low.</li>',
    '程序文件不完整，请重新安装 lite browser。': 'Program files are incomplete. Reinstall lite browser.',
    '窗口': 'Window',
    '立即挂起后台标签页': 'Suspend background tabs now',
    '立即清除 Cookie': 'Clear Cookies now',
    '立即清除历史记录': 'Clear history now',
    '立即清除缓存': 'Clear cache now',
    '第 {0} / {1} 个': '{0} / {1}',
    '等待中': 'Pending',
    '筛选：': 'Filter: ',
    '管理 Cookie 与缓存': 'Manage Cookies and Cache',
    '管理 Cookie 与缓存(M)...': 'Manage Cookies and Cache(M)...',
    '管理黑名单(L)...': 'Manage blacklist(L)...',
    '粘贴(P)': 'Paste(P)',
    '系统': 'System',
    '系统（64 位视图）': 'System (64-bit view)',
    '红包': 'red packet',
    '继续使用明文(&C)': 'Continue with plaintext(&C)',
    '继续访问会让本次连接失去证书保护，请不要在该网站输入密码或支付信息。': 'If you continue, this connection will lose certificate protection. Do not enter passwords or payment information on this site.',
    '继续访问（不推荐）(&P)': 'Continue anyway (not recommended)(&P)',
    '绿色挂锁 = HTTPS 加密连接（证书校验通过），': 'green padlock = HTTPS encrypted connection (certificate verified),',
    '缓存与站点数据': 'Cache and site data',
    '编辑(E)': 'Edit(E)',
    '编辑书签': 'Edit bookmark',
    '缩小(O)': 'Zoom out(O)',
    '缺少：': 'Missing: ',
    '网关超时': 'Gateway timeout',
    '网关错误': 'Gateway error',
    '网址': 'URL',
    '网址中使用了 @ 伪装真实域名（常见钓鱼手法）': 'URL uses @ to disguise the real domain (a common phishing trick)',
    '网址包含敏感词（': 'URL contains a sensitive word (',
    '网址包含敏感词：': 'URL contains a sensitive word: ',
    '网址异常冗长，可能隐藏真实跳转地址': 'URL is unusually long and may hide the real destination',
    '网站': 'Site',
    '网络': 'Network',
    '网络错误': 'Network error',
    '网页会打不开。为此提供了内置诊断工具：</p>': 'pages will not open. A built-in diagnostic tool is provided for this:</p>',
    '网页保存与打印': 'Saving and printing',
    '网页缩放': 'Page zoom',
    '网页脚本在<b>没有用户点击</b>的情况下弹出的窗口会被直接拦掉，': 'Windows opened by page scripts <b>without a user click</b> are blocked outright,',
    '自动选择（推荐）': 'Automatic (recommended)',
    '自定义值(C)：': 'Custom value(C): ',
    '自定义边框颜色': 'Custom border color',
    '自定义（在下方输入）': 'Custom (enter below)',
    '自签名': 'Self-signed',
    '要求登录后才能观看。未登录时页面会显示「出错啦」或要求登录。</li>': 'can only be watched after signing in. When you are not signed in, the page shows "Something went wrong" or asks you to sign in.</li>',
    '要迁移请先设置<b>口令</b>（否则其它机器的 DPAPI 解不开），': 'so before migrating, set a <b>passphrase</b> (otherwise DPAPI on another machine cannot unlock them),',
    '规则支持 example.com 与 *.example.com 两种写法。': 'Rules support both example.com and *.example.com.',
    '视频播放自检(V)': 'Video playback self-check (V)',
    '视频播放自检页。': 'Video playback self-check page.',
    '视频播放（哔哩哔哩等）': 'Video playback (Bilibili, etc.)',
    '视频解码：{1}': 'Video decoding: {1}',
    '记录浏览历史（含打开日期与时间）': 'Record browsing history (with date and time opened)',
    '设置': 'Settings',
    '设置(O)...': 'Settings (O)...',
    '设置(S)': 'Settings (S)',
    '设置加密口令': 'Set encryption passphrase',
    '设置口令(P)...': 'Set Passphrase (P)...',
    '设置口令失败：{0}': 'Failed to set passphrase: {0}',
    '证书不受信任': 'Certificate not trusted',
    '证书不受信任：{0}': 'Certificate not trusted: {0}',
    '证书中的主机名不正确': 'Certificate host name is incorrect',
    '证书名称': 'Certificate name',
    '证书已被吊销': 'Certificate has been revoked',
    '证书已过期': 'Certificate has expired',
    '证书无效': 'Certificate is invalid',
    '证书有效（颁发者：{0}）': 'Certificate valid (issuer: {0})',
    '证书有问题时弹出提示，由我决定是否继续': 'Warn me when a certificate has a problem and let me decide whether to continue',
    '证书校验用于确认网站身份并加密通信。关闭提示后，证书异常将按内核默认行为处理（通常直接拦截）。': "Certificate validation confirms a website's identity and encrypts traffic. If you turn off the warning, certificate problems are handled by the engine default (usually blocked outright).",
    '证书用于确认网站身份并加密通信。继续访问可能使您的信息被窃取或篡改。': "Certificates confirm a website's identity and encrypt traffic. Continuing may expose your information to theft or tampering.",
    '证书错误': 'Certificate error',
    '诊断报告已复制到剪贴板。': 'Diagnostic report copied to the clipboard.',
    '该任务正在下载，确定要取消并删除吗？': 'This task is downloading. Cancel and delete it?',
    '该域名使用了较高风险的后缀': 'This domain uses a higher-risk suffix',
    '该域名在您的黑名单中': 'This domain is on your block list',
    '该网址命中了本地可疑规则': 'This URL matched a local suspicious rule',
    '该网址命中本地可疑规则': 'This URL matched a local suspicious rule',
    '说明': 'Note',
    '说明：本程序使用 Edge WebView2 内核渲染网页。若系统缺少 WebView2 运行时，网页将无法显示，可点上面的按钮一键下载安装（安装过程由微软官方程序完成）。': "Note: This program uses the Edge WebView2 engine to render web pages. If the WebView2 Runtime is missing, pages cannot be displayed. Click the button above to download and install it in one step (installation is performed by Microsoft's official program).",
    '说明：缓存用于加速网页加载，清除后首次访问网站会稍慢；站点数据包含网页的本地存储与离线数据，清除可能导致网站设置丢失。': 'Note: The cache speeds up page loading, so the first visit to a site may be slower after clearing. Site data includes local storage and offline data; clearing it may lose website settings.',
    '请先打开一个标签页。': 'Open a tab first.',
    '请先选择要删除的 Cookie。': 'Select the cookies to delete first.',
    '请在 Windows 功能中启用 .NET Framework 4.8，或安装 .NET 运行时。': 'Enable .NET Framework 4.8 in Windows Features, or install the .NET runtime.',
    '请填写书签地址。': 'Enter a bookmark address.',
    '请手动打开测试页面：': 'Open the test page manually:',
    '请手动打开测试页面：\n{0}\n\n点击页面里的「开始游戏」即可。': 'Please open the test page manually:\n{0}\n\nThen click "Start Game" on the page.',
    '请按微软的安装向导完成安装（可能需要管理员确认），完成后回到这里点「重新检测」。': 'Follow Microsoft\'s setup wizard to finish the installation (administrator confirmation may be required), then return here and click "Check again".',
    '请检查磁盘空间与目录权限，或改用便携版放到可写目录。': 'Check disk space and folder permissions, or use the portable version in a writable folder.',
    '请求无效': 'Invalid request',
    '请求超时': 'Request timed out',
    '请求过于频繁': 'Too many requests',
    '请选择下载文件的保存目录：': 'Select the folder to save downloaded files:',
    '请选择默认下载目录：': 'Select the default download folder:',
    '账号': 'Account',
    '账户': 'Account',
    '路径': 'Path',
    '转到': 'Go',
    '输入加密口令': 'Enter encryption passphrase',
    '输入域名或名称关键字': 'Enter a domain or name keyword',
    '输入网址，或输入关键字后按回车搜索': 'Enter a URL, or enter keywords and press Enter to search',
    '过期': 'Expired',
    '过期时间': 'Expiry time',
    '运行状态': 'Running status',
    '返回安全页面(&B)': 'Back to safety (&B)',
    '还原(R)': 'Restore (R)',
    '这些是<b>启发式规则</b>，只用于识别可疑的 URL 特征，': 'These are <b>heuristic rules</b> used only to spot suspicious URL traits;',
    '这些组件随程序一起分发，缺失说明安装不完整。': 'These components ship with the program; if missing, the installation is incomplete.',
    '这是模拟器的固有限制。</li>': 'this is an inherent limitation of the emulator.</li>',
    '这通常说明系统的 WebView2 运行时缺少媒体组件。</p>': 'This usually means the system WebView2 Runtime is missing media components.</p>',
    '这里列出当前内核保存的全部 Cookie。删除后立即生效，已登录的网站可能需要重新登录。': 'This lists all cookies stored by the current engine. Deletions take effect immediately; sites you are signed in to may require signing in again.',
    '连接安全性': 'Connection security',
    '连接安全性详细信息': 'Connection security details',
    '连接已断开': 'Connection closed',
    '连接被中止': 'Connection aborted',
    '连接被重置': 'Connection reset',
    '连接超时': 'Connection timed out',
    '退出(&Q)': 'Exit (&Q)',
    '退出(X)': 'Exit (X)',
    '适合网页完全打不开、进不了设置时使用。</li>': 'useful when pages will not open at all and you cannot reach the settings.</li>',
    '选择 <b>Edge WebView2（Chromium，含 H.264/AAC）</b>，': 'select <b>Edge WebView2 (Chromium, includes H.264/AAC)</b>,',
    '选择下载目录': 'Choose download folder',
    '选择器': 'Selector',
    '选择边框颜色': 'Choose border color',
    '选择颜色(C)...': 'Choose Color (C)...',
    '都会跟着变换，保证可读性；也可以用菜单': 'changes with it to stay readable; you can also use the menu',
    '重做(R)': 'Redo (R)',
    '重启后应用）。</li>': 'applied after a restart).</li>',
    '重定向失败': 'Redirect failed',
    '重新检测(&R)': 'Check Again (&R)',
    '重新统计': 'Recount',
    '闲置时间超过(A)：': 'After idle for more than (A): ',
    '随时可在下载窗口或「设置 → 常规」中修改，也可勾选「每次下载都询问」。</li>': 'you can change it at any time in the downloads window or in "Settings → General", or check "Ask every time".</li>',
    '随程序分发的组件文件、pythonnet 互操作组件、.NET 运行时、用户数据目录可写性，': 'component files shipped with the program, pythonnet interop components, .NET runtime, and whether the user data directory is writable;',
    '隐私与安全': 'Privacy and security',
    '需要身份验证': 'Authentication required',
    '需要身份验证凭据': 'Authentication credentials required',
    '页面上会进入点选模式：鼠标移动时红框高亮当前元素，': 'and the page enters pick mode: a red box highlights the current element as the mouse moves,',
    '页面内查找': 'Find in page',
    '页面另存为': 'Save page as',
    '页面另存为(A)...': 'Save Page As (A)...',
    '页面已被删除': 'Page was deleted',
    '预设(U)：': 'Presets (U): ',
    '预读取当前网页中的链接（DNS 预解析 / 预连接，默认关闭）': 'Prefetch links on the current page (DNS prefetch / preconnect, off by default)',
    '首次下载时会提示选择': 'You will be prompted to choose on the first download',
    '首次下载，请设定默认的下载保存目录：': 'First download. Set the default folder for saving downloads:',
    '验证': 'Verify',
    '高风险域名后缀与敏感词同时出现': 'High-risk domain suffix and sensitive words appear together',
    '黄色警告 = HTTP 未加密连接；点击可查看详情。': 'yellow warning = unencrypted HTTP connection; click to see details.',
    '黑名单（拦截）': 'Block list (block)',
    '默认搜索引擎(S)：': 'Default search engine (S): ',
    '默认由 <b>Windows DPAPI</b> 保护（只有同一 Windows 账户能解开）。</li>': 'protected by <b>Windows DPAPI</b> by default (only the same Windows account can unlock it).</li>',
    '默认缩放比例(Z)：': 'Default zoom level (Z): ',
    '默认（跟随内核）': 'Default (follow engine)',
    '齐全（Core.dll {0} KB + 加载器）': 'Complete (Core.dll {0} KB + loader)',
    '（scrypt 派生密钥），便于把数据带到别的机器；启动时需要输入口令。</li>': '(the key is derived with scrypt), which makes it easy to carry your data to another machine; the passphrase is required at startup.</li>',
    '（{0} 条）': '({0} items)',
    '（只加载第一个，其余点击时再加载，以加快启动）。</li>': '(only the first is loaded, the rest load when clicked, to speed up startup).</li>',
    '（安全管理器未启用）': '(Security Manager not enabled)',
    '（已筛选，高亮显示匹配内容）': '(Filtered; matches highlighted)',
    '（当前使用：{0}）': '(Currently using: {0})',
    '（很多 Flash 站点不发跨域头，直接取会失败）。</li>': '(many Flash sites send no CORS headers, so fetching them directly fails).</li>',
    '（性能管理器未启用）': '(Performance Manager not enabled)',
    '（或「工具 → 标记并屏蔽广告元素」），': '(or "Tools → Mark and block ad elements"),',
    '（无）': '(None)',
    '（暂无书签）': '(No bookmarks)',
    '（未初始化数据保险库）': '(Data vault not initialized)',
    '（未报告）': '(Not reported)',
    '（移动端标识，网站会返回手机版页面）': '(Mobile identifier; websites return the mobile version)',
    '（约 2 MB）并启动安装，安装完成后回到该页点「重新检测」即可；': '(about 2 MB) and starts the installation; when it finishes, come back to this page and click "Check again";',
    '（经典 XP 外观请勿勾选），需重启生效。</li>': '(do not check it for the classic XP look); a restart is required.</li>',
    '（见设置）': '(see Settings)',
    '（超过天数的记录在启动时自动清理）。</li>': '(entries older than that are cleaned up automatically at startup).</li>',
    '）且未使用 HTTPS 加密': ') and not encrypted with HTTPS',
    '），并支持深色 / 浅色模式；自定义边框颜色会同时应用到标题栏与窗口边框。切换后立即生效，无需重启。': '), and supports dark / light mode; the custom border color is applied to both the title bar and window border. Changes take effect immediately; no restart needed.',
    '，Rust 编写的 Flash 运行时，编译成 WebAssembly），': ', a Flash runtime written in Rust and compiled to WebAssembly),',
}
